import gpufl as gfl
import gzip
import os
import re
import time
import tempfile
import shutil


def _read_channel_logs(session_dir, channel):
    """Return (paths, lines) for active or rotated files in one log channel."""
    active = {
        f"{channel}.log": (10**9, 0),
        f"{channel}.log.gz": (10**9, 1),
    }
    rotated_re = re.compile(rf"^{re.escape(channel)}\.(\d+)\.log(\.gz)?$")

    matches = []
    for entry in os.listdir(session_dir):
        path = os.path.join(session_dir, entry)
        if not os.path.isfile(path):
            continue
        if entry in active:
            matches.append((active[entry], path))
            continue
        match = rotated_re.match(entry)
        if match:
            index = int(match.group(1))
            compressed = 1 if match.group(2) else 0
            matches.append(((index, compressed), path))

    paths = [path for _, path in sorted(matches)]
    lines = []
    for path in paths:
        if path.endswith(".gz"):
            with gzip.open(path, 'rt') as f:
                lines.extend(f.readlines())
        else:
            with open(path, 'r') as f:
                lines.extend(f.readlines())
    return paths, lines


def test_pipeline():
    print("--- Starting GPUFL Multi-Log Pipeline Verification ---")
    temp_dir = tempfile.mkdtemp()
    log_base_name = "ci_test"
    log_base_path = os.path.join(temp_dir, log_base_name)
    print(f"1. Log path set to: {log_base_path}")

    keep = False
    try:
        print("2. Initializing GPUFL...")
        # Trace = activity trace (kernels, memcpy, sync), no sampling. We
        # exercise the CUPTI activity path here so the pipeline smoke test
        # covers it; the no-CUPTI Monitor mode is covered by the
        # engine-coverage suite.
        res = gfl.init("CI_Test_App", log_base_path, True, 50,
                       profiling_engine=gfl.ProfilingEngine.Trace)
        print(f"   Result: {res}")
        if res is False:
            print("\n[CI-INFO] GPUFL initialized in Stub Mode (No GPU detected).")
            print("          This is expected behavior on GitHub Action Runners.")
            print("          Skipping log file verification since no logs are generated.")

            # Clean up and exit successfully (Exit Code 0)
            shutil.rmtree(temp_dir, ignore_errors=True)
            return

        print("3. Running Scope...")
        with gfl.Scope("ci_scope_01", "test_tag"):
            time.sleep(0.1)
            x = 0
            for i in range(1000): x += i

        print("4. Shutting down...")
        gfl.shutdown()

        print("5. Verifying Log Files...")
        # v1.2+ layout: <base_path>/<session_id>/<channel>.log[.gz]
        # The session_id subdir is generated by gpufl.init() and isn't
        # known to the test in advance - we discover it by listing
        # log_base_path. On clean shutdown the rotator gzips the active
        # .log → .log.gz (see log_rotator.cpp::compressActive); accept
        # either form so the test still passes if compress_rotated is
        # ever turned off.
        if not os.path.isdir(log_base_path):
            print(f"FAILED: Base log dir not created: {log_base_path}")
            print(f"   Contents of {temp_dir}: {sorted(os.listdir(temp_dir))}")
            keep = True
            raise SystemExit(1)

        session_dirs = [
            d for d in sorted(os.listdir(log_base_path))
            if os.path.isdir(os.path.join(log_base_path, d))
        ]
        print(f"   Session dirs under {log_base_path}: {session_dirs}")
        if len(session_dirs) != 1:
            print(f"FAILED: Expected exactly one session dir, found {len(session_dirs)}.")
            keep = True
            raise SystemExit(1)

        session_dir = os.path.join(log_base_path, session_dirs[0])
        for entry in sorted(os.listdir(session_dir)):
            full = os.path.join(session_dir, entry)
            fsize = os.path.getsize(full) if os.path.isfile(full) else 0
            print(f"    - {entry} [size={fsize}]")

        categories = ["scope", "system"]
        for cat in categories:
            found_paths, lines = _read_channel_logs(session_dir, cat)
            if not found_paths:
                print(f"FAILED: Expected {cat} log files in {session_dir}")
                keep = True
                raise SystemExit(1)

            found_names = [os.path.basename(path) for path in found_paths]
            print(f"   [OK] Found {cat} log: {found_names}")

            has_init = any('"type":"job_start"' in line for line in lines)
            if not has_init:
                print(f"FAILED: {cat} log missing job_start event.")
                keep = True
                raise SystemExit(1)

        print("\nSUCCESS: All log files created and content verified.")

    except Exception as e:
        print(f"\nCRITICAL FAILURE: {e}")
        keep = True
        raise

    finally:
        if keep:
            print(f"Keeping temp dir for inspection: {temp_dir}")
        else:
            shutil.rmtree(temp_dir, ignore_errors=True)

if __name__ == "__main__":
    test_pipeline()
