#pragma once

#include <cstddef>
#include <memory>
#include <mutex>
#include <string>
#include <vector>

#include "gpufl/core/model/serializable.hpp"

namespace gpufl {

class ILogSink;

/**
 * Central log dispatcher - every event emitted via the runtime goes
 * through Logger::write(), which broadcasts the serialized NDJSON
 * line to every registered {@link ILogSink}.
 *
 * The default session uses a single {@link FileLogSink} (preserves
 * the original per-channel file layout on disk). Additional sinks can
 * be attached via {@link addSink} - e.g. test recorders, alternative
 * file formats. Live HTTP upload used to live here (`HttpLogSink`) but
 * was removed in favor of the post-shutdown {@link gpufl::uploadLogs}
 * deferred-upload path; sinks are now strictly local.
 *
 * Thread safety: {@link write} is safe to call from any thread.
 * The sink vector itself is only modified from the init() / shutdown()
 * path (no concurrent addSink during writes in practice) and is
 * locked with a mutex on reads anyway.
 */
class Logger {
   public:
    /**
     * Default per-file rotation threshold. Referenced by the uploader
     * (upload_logs.cpp) - since U1 a rotated file is the upload unit
     * (one POST per file), so its size guards derive from this value
     * and the backend's decompressed body cap is sized at 2× it. If
     * this grows, grow the backend's
     * StreamEventIngestionConstants.MAX_DECOMPRESSED_BODY_BYTES in
     * lockstep.
     */
    static constexpr std::size_t kDefaultRotateBytes = 64 * 1024 * 1024;

    struct Options {
        std::string base_path;
        /**
         * Session ID - used as a subdirectory under `base_path` so each
         * profiling session's files are isolated:
         *
         *   <base_path>/<session_id>/device.log
         *   <base_path>/<session_id>/scope.log
         *   <base_path>/<session_id>/system.log
         *
         * Generated by gpufl::init() and threaded through to the
         * rotator. v1.2+ format; the pre-v1.2 flat layout
         * (`<base>.<channel>.log` with no subdir) is no longer written -
         * the uploader detects it only to emit a migration warning.
         */
        std::string session_id;
        /**
         * Rotate a channel file once the next write would push it past
         * this many bytes (checked BEFORE writing, so a file only ever
         * exceeds it by at most one event line). Keep ≤ half the
         * backend's decompressed body cap - see kDefaultRotateBytes.
         */
        std::size_t rotate_bytes = kDefaultRotateBytes;
        std::size_t max_files = 100;
        bool compress_rotated = true;
        bool flush_always = false;
        int system_sample_rate_ms = 0;
    };

    Logger();
    ~Logger();

    /**
     * Initialize the logger with the default FileLogSink attached.
     * Returns false if the base_path is empty (the file sink cannot
     * open without a path).
     */
    bool open(const Options& opt);

    /**
     * Close and release all attached sinks. Safe to call multiple
     * times; safe to call on an already-closed logger.
     */
    void close();

    /**
     * Attach an additional sink. Ownership transfers to the Logger.
     * Call before the first write() to avoid lost lines - sinks added
     * after events have already flowed will not back-fill.
     */
    void addSink(std::unique_ptr<ILogSink> sink);

    /**
     * Serialize the model and broadcast to all sinks on the model's
     * declared channel(s).
     */
    void write(const IJsonSerializable& model);

   private:
    Options opt_;
    std::vector<std::unique_ptr<ILogSink>> sinks_;
    mutable std::mutex sinks_mu_;
};

}  // namespace gpufl
