#pragma once

#include <cstddef>
#include <cstdint>
#include <functional>
#include <memory>
#include <mutex>
#include <string>
#include <vector>

#include "gpufl/core/model/serializable.hpp"

namespace gpufl {

class ILogSink;
class LifecycleControlJournal;

/**
 * Central log dispatcher - every event emitted via the runtime goes
 * through Logger::write(), which broadcasts the serialized NDJSON
 * line to every registered {@link ILogSink}.
 *
 * The default session uses a single {@link FileLogSink} (preserves
 * the original per-channel file layout on disk). Additional sinks can
 * be attached via {@link addSink} - e.g. test recorders, alternative
 * file formats. Live HTTP upload used to live here (`HttpLogSink`) but
 * was removed in favor of the post-shutdown {@link gpufl::uploadLogs}
 * deferred-upload path; sinks are now strictly local.
 *
 * Thread safety: {@link write} is safe to call from any thread.
 * The sink vector itself is only modified from the init() / shutdown()
 * path (no concurrent addSink during writes in practice) and is
 * locked with a mutex on reads anyway.
 */
class Logger {
   public:
    /**
     * Default per-file rotation threshold. Referenced by the uploader
     * (upload_logs.cpp) - since U1 a rotated file is the upload unit
     * (one POST per file), so its size guards derive from this value
     * and the backend's decompressed body cap is sized at 2× it. If
     * this grows, grow the backend's
     * StreamEventIngestionConstants.MAX_DECOMPRESSED_BODY_BYTES in
     * lockstep.
     */
    static constexpr std::size_t kDefaultRotateBytes = 64 * 1024 * 1024;
    // A profiler must not exhaust the filesystem used by the target
    // application during a prolonged agent/backend outage. These are
    // session-wide safety limits, not retention policy: acknowledged
    // payload deletion still belongs exclusively to the agent.
    static constexpr std::uint64_t kDefaultMaxSpoolBytes =
        4ull * 1024 * 1024 * 1024;
    static constexpr std::uint64_t kDefaultMinFreeBytes =
        512ull * 1024 * 1024;

    struct Options {
        std::string base_path;
        /**
         * Session ID - used as a subdirectory under `base_path` so each
         * profiling session's files are isolated:
         *
         *   <base_path>/<session_id>/device.log
         *   <base_path>/<session_id>/scope.log
         *   <base_path>/<session_id>/system.log
         *
         * Generated by gpufl::init() and threaded through to the
         * rotator. v1.2+ format; the pre-v1.2 flat layout
         * (`<base>.<channel>.log` with no subdir) is no longer written -
         * the uploader detects it only to emit a migration warning.
         */
        std::string session_id;
        /**
         * Rotate a channel file once the next write would push it past
         * this many bytes (checked BEFORE writing, so a file only ever
         * exceeds it by at most one event line). Keep ≤ half the
         * backend's decompressed body cap - see kDefaultRotateBytes.
         */
        std::size_t rotate_bytes = kDefaultRotateBytes;
        /**
         * Also rotate once the data in the current window spans more
         * than this many milliseconds, measured on the MONOTONIC clock
         * from the window's first write. 0 disables the time trigger
         * (default). An EMPTY window is never rotated, so idle channels
         * produce no empty files.
         *
         * Two paths reach the deadline: the check before each write
         * (immediate on busy channels) and the collector's periodic
         * rotateDueWindows() beat, which is what publishes a window
         * whose channel has gone quiet. Worst-case publish latency is
         * therefore roughly rotate_after_ms + one beat interval
         * (~250 ms) + the cutover rename; compression and the publish
         * retry happen afterwards on the retirement worker, so they add
         * to the window's arrival time but never to the caller's.
         */
        std::int64_t rotate_after_ms = 0;
        /**
         * Monotonic now() in milliseconds, injectable so unit tests
         * drive rotation with a fake clock instead of sleeps. Unset
         * (default) → std::chrono::steady_clock. Never wall clock:
         * NTP/DST jumps must not fire or starve rotation windows.
         */
        std::function<std::int64_t()> now_ms;
        /**
         * Test-only synchronization hook invoked by the retirement worker
         * immediately before it starts a slow export. Production leaves this
         * empty. It lets concurrency tests block gzip deterministically and
         * prove the cutover caller has already returned.
         */
        std::function<void()> before_retired_export;
        /**
         * Called synchronously after FileLogSink accepts serialized NDJSON
         * bytes. The value includes the trailing newline and every channel
         * copy actually written (Channel::All therefore reports four copies
         * when all default channels are open). Dropped or failed writes do not
         * invoke it. The callback must be non-blocking, must not throw, and
         * must not re-enter Logger.
         */
        std::function<void(std::uint64_t bytes)> on_serialized_bytes;

        /**
         * Write immutable lifecycle control records beside the normal NDJSON
         * windows. This remains OFF until the launcher has confirmed an agent
         * that understands the control endpoint; old agents continue to use
         * the ordinary data-plane lifecycle records as their fallback.
         */
        bool lifecycle_control_journal_enabled = false;

        /**
         * Stop accepting new profiling events once this session's on-disk
         * spool reaches the limit. 0 disables the per-session byte limit.
         * Saturation is terminal for the session and is recorded durably so
         * upload cannot later claim the resulting partial profile is complete.
         */
        std::uint64_t max_spool_bytes = kDefaultMaxSpoolBytes;
        /**
         * Also stop before the filesystem's available space drops below this
         * reserve. 0 disables the free-space guard.
         */
        std::uint64_t min_free_bytes = kDefaultMinFreeBytes;
        bool compress_rotated = true;
        bool flush_always = false;
        int system_sample_rate_ms = 0;
    };

    Logger();
    ~Logger();

    /**
     * Initialize the logger with the default FileLogSink attached.
     * Returns false if the base_path is empty (the file sink cannot
     * open without a path).
     */
    bool open(const Options& opt);

    /**
     * Replace FileLogSink byte accounting before this logger's first write.
     * The callback must remain non-blocking, non-throwing, and must not
     * re-enter Logger.
     */
    void setSerializedBytesCallbackBeforeFirstWrite(
        std::function<void(std::uint64_t)> callback);

    /**
     * Close and release all attached sinks. Safe to call multiple
     * times; safe to call on an already-closed logger.
     */
    void close();

    /**
     * Attach an additional sink. Ownership transfers to the Logger.
     * Call before the first write() to avoid lost lines - sinks added
     * after events have already flowed will not back-fill.
     */
    void addSink(std::unique_ptr<ILogSink> sink);

    /**
     * Serialize the model and broadcast to all sinks on the model's
     * declared channel(s).
     */
    void write(const IJsonSerializable& model);

    /**
     * Forward the collector's periodic beat to every sink so overdue
     * transport windows publish without waiting for the next write.
     */
    void rotateDueWindows();

   private:
    Options opt_;
    std::vector<std::unique_ptr<ILogSink>> sinks_;
    std::unique_ptr<LifecycleControlJournal> lifecycle_control_journal_;
    mutable std::mutex sinks_mu_;
};

}  // namespace gpufl
